"""users table

Revision ID: 9640c5307dfe
Revises: 49117740c8c0
Create Date: 2020-02-23 09:25:42.746439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9640c5307dfe'
down_revision = '49117740c8c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('food_supplier', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_user_food_supplier'), 'user', ['food_supplier'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_food_supplier'), table_name='user')
    op.drop_column('user', 'food_supplier')
    # ### end Alembic commands ###
